apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "my-test"
  description: "A cool quarkus app test"
  annotations:
    backstage.io/source-location: url:https://github.com/edubois10/rhdh_techdocs_plugin
    backstage.io/techdocs-ref: url:https://github.com/edubois10/rhdh_techdocs_plugin/docs
    github.com/project-slug: edubois10/rhdh_techdocs_plugin
  tags:
    - java
    - quarkus
  links:
    - url: https://devspaces.apps.cluster-mmdsx.sandbox1108.opentlc.com/#https://github.com/edubois10/rhdh_techdocs_plugin
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: https://devspaces.apps.cluster-mmdsx.sandbox1108.opentlc.com/#https://github.com/edubois10/rhdh_techdocs_plugin?che-editor=che-incubator/che-idea/latest
      title: OpenShift Dev Spaces (JetBrains IntelliJ)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "edubois10"
  providesApis:
    - "my-quarkus-app"
